### ISSUE TITLE
Please add a .netstandard 2.0 target that doesn't rely on System.Runtime

### ISSUE THREAD

**Issue by borbmizzet** [JetBrains/ExternalAnnotations#121]
The dependency of this package on System.Runtime can cause mscorlib conflicts in Xamarin projects that reference .netstandard 2.0 libraries that reference this.  Please add a .netstandard 2.0 target to the nuget package that doesn't require System.Runtime, as it should no longer be necessary to explicitly reference that dll in .netstandard 2.0.

**Comment by derigel23** [comment]
@borbmizzet it's fixed in 2018.2.1 version of the package.
https://www.nuget.org/packages/JetBrains.Annotations/2018.2.1
