### ISSUE TITLE
[CanBeNull] System.Windows.Controls.GridViewColumn.DisplayMemberBinding

### ISSUE THREAD

**Issue by drewnoakes** [JetBrains/ExternalAnnotations#13]
This annotation is missing. In fact I can't find any reference to the `GridViewColumn` class in `System.Windows.Controls`.

https://github.com/JetBrains/ExternalAnnotations/blob/master/Annotations/.NETFramework/System.Windows.Controls/2.0.5.0.Nullness.Gen.xml

Happy to add this if it'll be merged. Seems that this repo isn't actually being used. Is that the case?

**Comment by derigel23** [comment]
Hi @drewnoakes!

It's fully functional and live repo. And it's using. Updating of annotation usually is done simultaneously with release R# itself. About your case, yes it's missing, but it should be not in System.Windows.Controls but in PresentationFramework (groupping by assembly name, not namespace). You are talking about this property https://msdn.microsoft.com/en-us/library/system.windows.controls.gridviewcolumn.displaymemberbinding(v=vs.100).aspx, right?

**Comment by drewnoakes** [comment]
Good to hear. Thanks for the fix.

Are these definitions released independently of R#? Do we have to wait for a new version of R# to get these updates?

**Comment by derigel23** [comment]
In general, yes, independently. But due to massive changes for ASP.NET Core 1.0 latest annotations changes have no meaning without support from latest R# itself. So, package with recently changes marked as pre-release and available only in EAP builds.
