### ISSUE TITLE
CanBeNull annotation for Marshal.PtrToStructure

### ISSUE THREAD

**Issue by SirDuke** [JetBrains/ExternalAnnotations#132]
https://referencesource.microsoft.com/mscorlib/R/48a38ffe8a227f92.html

**Comment by NN---** [comment]
.NET docs doesn't indicate returning null:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?view=netframework-4.7.2#System_Runtime_InteropServices_Marshal_PtrToStructure_System_IntPtr_System_Type_

```
Returns
Object

A managed object containing the data pointed to by the ptr parameter.
```

As well correct way is to use ContractAnnotation and not CanBeNull. 
https://www.jetbrains.com/help/resharper/Contract_Annotations.html

```cs
[ContractAnnotation("p:null=>null")]
static object F(IntPtr p)
static object F(IntPtr p)
{
	// ReSharper disable once AssignNullToNotNullAttribute
	if (p == IntPtr.Zero) return null;
	return "";
}

var e = F(IntPtr.Zero);
var p = e.GetType(); // Possible NRE

var ee = F((IntPtr)1);
var pp = ee.GetType(); // No warnings
```

**Comment by NN---** [comment]
https://github.com/dotnet/dotnet-api-docs/issues/1024

**Comment by SirDuke** [comment]
decided not to add annotations. See discussion at https://github.com/JetBrains/ExternalAnnotations/pull/158
