### ISSUE TITLE
Ability to generate MyLibrary.ExternalAnnotations.xml during build or otherwise

### ISSUE THREAD

**Issue by drewnoakes** [JetBrains/ExternalAnnotations#15]
Given the attributes in the `JetBrains.Annotations` NuGet package are `[Conditional("JETBRAINS_ANNOTATIONS")]`, they're not present in compiled library code (I could set the condition symbol, but I'm happy leaving them out of the DLL's metadata).

I'd like users of my library to benefit from these annotations, but I don't want to maintain the XML by hand.

Is it possible to have them generated automatically, perhaps as part of the build process?

If so, would including them in nupkg files be enough to have them picked up by users of my NuGet packages?

**Comment by derigel23** [comment]
@drewnoakes yes, putting annotations near to the library dll will be enough.
About generating them there is already similar request in our tracker https://youtrack.jetbrains.com/issue/RSRP-453476

**Comment by drewnoakes** [comment]
Thanks, Slava.
