### ISSUE TITLE
Package install fails saying not compatible with .Net v4.7.2

### ISSUE THREAD

**Issue by QuentinSuckling** [JetBrains/ExternalAnnotations#166]
Hi,

Upgrading from 10.2.57 to 10.2.60 fails with this - 

Could not install package 'Wave 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

Cheers,
Quentin

**Comment by derigel23** [comment]
Quentin where are you trying to install this package?

**Comment by QuentinSuckling** [comment]
Visual Studio 2017.

I've tried a few times now over the last few weeks and get the same thing.
Should I try removing the External Annotations extension completely then try reinstalling it?

**Comment by derigel23** [comment]
I am asking to which project are you trying to install this package. It's not regular package it's ReSharper extension and should be installed throuh R# extension manager.

**Comment by QuentinSuckling** [comment]
I've always installed it though NuGet manager in VS and it's worked fine.
Are you saying I shouldn't be doing that?

**Comment by derigel23** [comment]
It worked fine but had no effect at all )
External annotations are bundled with ReSharper & updated automatically.
Installing them to project has no meaning.
