### ISSUE TITLE
Mark ExceptionDispatchInfo::Throw() as "always throw"

### ISSUE THREAD

**Issue by ViIvanov** [JetBrains/ExternalAnnotations#17]
This method always throws an exception: http://referencesource.microsoft.com/#mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs,fc3b312e2d0ab87a

But R# does not know about it:
![image](https://cloud.githubusercontent.com/assets/795200/16847378/6526d0e6-49f9-11e6-9248-93101b0e854d.png)

// I will try to send PR for this

**Comment by derigel23** [comment]
It's already marked with necessary annotation https://github.com/JetBrains/ExternalAnnotations/blob/8b9d8a1726ba096dc7fdf3deda4cb8dbfd1bb787/Annotations/.NETFramework/System/Attributes.xml#L12

**Comment by derigel23** [comment]
@ViIvanov, issue is not related to external annotations - please file an issue in ReSharper tracker.

**Comment by derigel23** [comment]
Oh, and it's not ReSharper's issue at all.

**Comment by chrisoverzero** [comment]
@derigel23 I don't think you read this ticket carefully. `Debug.Fail` is not the method in question. It is `ExceptionDispatchInfo::Throw`. (That is, the instance method `Throw`.)

**Comment by derigel23** [comment]
@chrisoverzero agree. That's why PR is always better :)
