### ISSUE TITLE
Enumerable.AsEnumerable is not marked with [NotNull]

### ISSUE THREAD

**Issue by NN---** [JetBrains/ExternalAnnotations#170]

**Comment by SirDuke** [comment]
It can return null if input parameter is null, but "ContractAnnotation("null=>null;notnull=>notnull")" generates a lot of noise in "Optimistic" analysis mode. Need to properly handle it in ReSharper: https://youtrack.jetbrains.com/issue/RSRP-477158

**Comment by Mertsch** [comment]
https://youtrack.jetbrains.com/issue/RSRP-477158 is supposed to be fixed now
```
Ivan Serduk 2020-04-06T11:57:51
resolved date: None ⟶ 2020-04-06
State: Submitted ⟶ Fixed
```
