### ISSUE TITLE
Annotate numericTypes.CompareTo for for .NetCore as [Pure]

### ISSUE THREAD

**Issue by TessenR** [JetBrains/ExternalAnnotations#172]
Currently missing annotations cause false positive warnings like this:

![image](https://user-images.githubusercontent.com/5566206/60427637-c5435200-9bff-11e9-8e9e-9dc2defa51d1.png)

**Comment by SirDuke** [comment]
fixed in https://github.com/JetBrains/ExternalAnnotations/commit/3562d987e643343586645d0463ccb55194785d7e
