### ISSUE TITLE
Warning: Can't find annotations library for .NETFramework,Version=v0.0

### ISSUE THREAD

**Issue by IbrahimUmar** [JetBrains/ExternalAnnotations#173]
Hi , what does this error means? and whats the solution of this. Resharper taking 15 minutes to start

    

Warning: Can't find annotations library for .NETFramework,Version=v0.0

**Comment by SirDuke** [comment]
looks like a ReSharper's issue. Please, submit a request via Rider's menu (Help->Contact Support) or Visual Studio's menu (Extensions->ReSharper->help-> report a bug) or directly to https://youtrack.jetbrains.com
