### ISSUE TITLE
Annotate `Stream.Read` as `MustUseReturnValue`

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ExternalAnnotations#225]
The `Stream.Read` method, and similar methods such as `BinaryReader.Read` are allowed to return _fewer_ bytes than what the user asked for. Calling them without taking the result into account is a bug waiting to happen.

As a concrete example, the behavior of `GZipStream` [changed in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams), and it now can return fewer bytes than what the user asked for.

**Comment by adamsitnik** [comment]
As a person who "owns" Stream and uses Rider daily I would really love to see it happen. The more people are aware of it, the better.

**Comment by ltrzesniewski** [comment]
@sirduke Thanks!

Could you please also add annotations for `BinaryReader.Read(byte[],int,int)` and `BinaryReader.Read(Span<byte>)`? These methods simply return the result of `Stream.Read`. Thanks!

**Comment by ltrzesniewski** [comment]
Thanks again! 🙂
