### ISSUE TITLE
DependencyObject.GetValue can return null

### ISSUE THREAD

**Issue by drewnoakes** [JetBrains/ExternalAnnotations#33]

**Comment by derigel23** [comment]
Hi @drewnoakes!
Can you remind me when DependencyObject.GetValue can return null?
Thanks in advance!

**Comment by drewnoakes** [comment]
If you call `SetValue` with a null, it can return `null`. A property might also have a default value of null.

Dependency properties use the special `UnsetValue` to indicate the absence of a value. `null` is a valid value.

https://msdn.microsoft.com/en-us/library/system.windows.dependencyproperty.unsetvalue%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by appel1** [comment]
This causes warnings for every dependency property getter for properties with a value type. Can GetValue return null for a dependency property configured with a value type? Is there anyway to disable this warning for this specific case?

**Comment by SirDuke** [comment]
Removed nullness annotations for DependencyObject.GetValue because it generates false positives. See https://youtrack.jetbrains.com/issue/RSRP-465624
