### ISSUE TITLE
XNodeNavigator.XPathSelectElement can be null

### ISSUE THREAD

**Issue by drewnoakes** [JetBrains/ExternalAnnotations#44]
Full .NET framework.

**Comment by derigel23** [comment]
@drewnoakes is it internal class?

**Comment by drewnoakes** [comment]
On my phone. From memory it's an extension method.

**Comment by derigel23** [comment]
Please, provide full XML Doc ID. Can't find it.

**Comment by drewnoakes** [comment]
Not sure what an XML Doc ID is, so hopefully this is enough info.

Class `Extensions` in `System.Xml.XPath` has several extension methods for `XNode`. Annotations apply to all overloads.

XPathEvaluate -> NotNull
XPathSelectElement -> CanBeNull
XPathSelectElements ->NotNull

FYI R# navigation took me to file: ~\AppData\Local\Symbols\src\Source\01586.00\Source\ndp\fx\src\XLinq\System\Xml\Linq\XPathNavigator.cs
