### ISSUE TITLE
Member names should be consistent

### ISSUE THREAD

**Issue by tom-englert** [JetBrains/ExternalAnnotations#49]
Names for methods with no parameters should either all end with () or all without ()

e.g. `M:Microsoft.CSharp.Error.NotImplemented` 
should be `M:Microsoft.CSharp.Error.NotImplemented()`

There are 1530 methods with () and 15105 without ()

**Comment by tom-englert** [comment]
From https://msdn.microsoft.com/en-us/library/fsbx0t7x.aspx:

- No whitespace is in the string. (=> #47, #48)
- For properties and methods, if there are arguments to the method, the argument list enclosed in parentheses follows. *If there are no arguments, no parentheses are present*.

**Comment by tom-englert** [comment]
Looks like most of the methods that end with () are not methods without arguments, but the arguments are just missing, so all of these are just dead code.

**Comment by tom-englert** [comment]
@derigel23: so you have turned discoverable dead code into undiscoverable dead code ...

**Comment by derigel23** [comment]
it's not dead code - it's wrong attributes. Most of them in generated annotations and generator should be fixed and annotations should be regenerated.

**Comment by tom-englert** [comment]
All of these are method signatures of methods that don't exist - that's  what I meant with "dead code".
Are these xml's prefixed with a version number used at runtime? (e.g. 4.0.0.0.System.xml and 3.0.0.0.System.xml)

**Comment by derigel23** [comment]
What do you mean by run-time? In R# analyses? Yes. But as you pointed attributes weren't applied to those members since signatures were wrong and if some of them are still wrong (i.e. methods with parameters but not properties) there will not be applied still ad it was before.
