### ISSUE TITLE
~2000 missing or wrong annotations!

### ISSUE THREAD

**Issue by tom-englert** [JetBrains/ExternalAnnotations#50]
After getting a lot of false positives with R# I have compared the ExternalAnnotations with [Code Contracts](https://github.com/Microsoft/CodeContracts) and found a lot of differences.

While 3933 methods/props have identical nullability contracts, 1091 methods/props are missing at all, and 679 methods/props are different (mostly parts missing on R# side).

I have attached the results of my analysis, where `RS*` are the normalized ExternalAnnotations and `CC*` are the corresponding contracts exported from the Code Contracts project. All files are in ExternalAnnotations xml format.

`OK` are the ones where both have the same outcome.
`CC` and `RS` contain the the differences (compare both folders with e.g. BeyondCompare)
`CCOnly` are the ones defined only in Code Contracts and missing in R#

For the differences most times CC is more exact, but not always, so these would need an extra review.

[Contracts.zip](https://github.com/JetBrains/ExternalAnnotations/files/672224/Contracts.zip)

**Comment by SirDuke** [comment]
@tom-englert , thank you. Your annotations have been merged.
