### ISSUE TITLE
Missing ContractAnnotation("notnull => notnull")

### ISSUE THREAD

**Issue by tom-englert** [JetBrains/ExternalAnnotations#53]
Methods that can infer result nullability from parameter nullability do not have a ContractAnnotation attribute.

**Comment by derigel23** [comment]
@tom-englert any specific examples? It's too general.

**Comment by derigel23** [comment]
Ok, I see -it's about #54

**Comment by tom-englert** [comment]
Sorry, I missed to reference this...
