### ISSUE TITLE
Mark NugetPackage as DevelopmentDependency

### ISSUE THREAD

**Issue by BenKmann** [JetBrains/ExternalAnnotations#58]
If you add `<developmentDependency>true</developmentDependency>`
in your Metadata Block in your Nuspec File, it will install itself as a Development Dependency.
You can see it for Example here [Nuspec](https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/CodeCracker.nuspec#L22)

**Comment by derigel23** [comment]
@BenKmann why do you need it? this package is not supposed to be installed in regular project.
