### ISSUE TITLE
Merge from Community Resharper External Annotations

### ISSUE THREAD

**Issue by magol** [JetBrains/ExternalAnnotations#6]
Most of https://github.com/robv8r/resharper-annotations should be possible to Merga in

**Comment by derigel23** [comment]
Fell free to send PR! ;)

**Comment by robv8r** [comment]
Howdy.  I'll be happy to contribute and merge the Community Resharper External Annotations to this "official" repo.  I'll probably still keep the Community version out there for those things that don't either don't make sense to merge, or that the owners of this repo prefer to keep out of the official version.

@derigel23 
I'll start with a few of the ones I think will make the most sense to merge.  I prefer to send a larger number of smaller PR's rather that one big huge one.  Is that ok?

**Comment by derigel23** [comment]
@robv8r totally fine
