### ISSUE TITLE
Can't find it in Extension Manager?

### ISSUE THREAD

**Issue by sooqua** [JetBrains/ExternalAnnotations#63]
I am using Visual Studio 2017 and ReSharper 2016.3.2
For some reason I can't find this package https://resharper-plugins.jetbrains.com/packages/ReSharper.ExternalAnnotations/ in my Extension Manager. When I search for `External Annotations` I get only this: `Community ReSharper External Annotations`
I've installed the nuget package: https://www.nuget.org/packages/JetBrains.ExternalAnnotations/ but I'm not sure if it's the same thing? Can someone clarify this for me?
Thanks.

**Comment by derigel23** [comment]
@sooqua you don't need to install package explicitly anymore in 2016.x and later. It's updated automatically.
