### ISSUE TITLE
Directory.Exists -> true means path != null

### ISSUE THREAD

**Issue by drewnoakes** [JetBrains/ExternalAnnotations#79]

**Comment by michael-damatov** [comment]
The annotation is correct 

    [ContractAnnotation("null=>false")]

which means `path == null` -> `false`, but not vice versa!

**Comment by drewnoakes** [comment]
@michael-damatov are you saying there's no need for an additional annotation? It seems that if the return value is true, then path must be non-null.

**Comment by michael-damatov** [comment]
@drewnoakes: correct

**Comment by drewnoakes** [comment]
Here's an example that better shows what I meant.

```c#
string dir = MightBeNull();

if (Directory.Exists(dir))
{
    if (dir == null) { /* impossible */ }
}
```

**Comment by SirDuke** [comment]
@drewnoakes is not warning shown on "dir == null" ?

**Comment by drewnoakes** [comment]
I see the expected warning in Rider 2017.2 EAP (Build #RD-172.4144.808) for a net45 project, but not for netstandard1.3. Apologies for missing that from the original post, and for subsequent confusion.

So the problem appears to be with .NET Standard annotations.
