### ISSUE TITLE
String.Empty should be NoNull for .NETCore

### ISSUE THREAD

**Issue by takerukoushirou** [JetBrains/ExternalAnnotations#82]
The annotation is currently missing for .NETCore but exists for .NETFramework.
- [.NETCore Nullness.Manual.xml](https://github.com/JetBrains/ExternalAnnotations/blob/master/Annotations/.NETCore/System.Runtime/Nullness.Manual.xml)
- [.NETFramework Nullness.Manual.xml](https://github.com/JetBrains/ExternalAnnotations/blob/master/Annotations/.NETFramework/mscorlib/Nullness.Manual.xml)

**Comment by derigel23** [comment]
@takerukoushirou feel free to submit PR
