### ISSUE TITLE
DbCommand.ExecuteReaderAsync should be NotNull and ItemNotNull

### ISSUE THREAD

**Issue by proff** [JetBrains/ExternalAnnotations#94]
like it's sync analogs

**Comment by SirDuke** [comment]
Is there any documentation says that "ExecuteReaderAsync" should return not-null task with not-null result?

**Comment by SirDuke** [comment]
Actually, IDbCommand.ExecuteReader can return null - for example, OldDbCommand.ExecuteReader returns null in some cases
