### ISSUE TITLE
DirectorySearcher.FindOne can return null

### ISSUE THREAD

**Issue by SirDuke** [JetBrains/ExternalAnnotations#98]
https://github.com/JetBrains/ExternalAnnotations/blob/5f5c73106e560ba6d2c185c374ff5737550bcb89/Annotations/.NETFramework/System.DirectoryServices/Annotations.xml#L3576

MSDN and actual implementations contradicts  CodeContracts:
https://github.com/Microsoft/CodeContracts/issues/50
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.directorysearcher.findone?view=netframework-4.7.1

**Comment by Memphizzz** [comment]
+1 ReSharper suggests to remove "if(result == null)" even though it happens sometimes that it actually is null.
